package com.github.kr328.clash.companion

import java.security.SecureRandom

/**
 * PIN-assisted pairing state (PROTOCOL.md §6.4) — the camera-less path used by a PC controller
 * (e.g. SlothClash). The agent shows a short numeric PIN on its screen; the controller submits it
 * to `POST /v1/pair`. The PIN is single-use, expiring (≤60s) and rate-limited (≤5 attempts).
 *
 * Process-wide singleton: generated by the agent UI (CompanionActivity), verified by the gateway
 * server — both run in the app process.
 */
object CompanionPin {
    private const val TTL_MS = 60_000L
    private const val MAX_ATTEMPTS = 5
    private const val DIGITS = 6

    private val random = SecureRandom()

    enum class Result { OK, WRONG, RATE_LIMITED, EXPIRED }

    private class Active(val pin: String, val expiresAt: Long, var attempts: Int)

    @Volatile
    private var active: Active? = null

    /** Generate and arm a fresh PIN (replacing any previous one). Returns it for on-screen display. */
    @Synchronized
    fun generate(): String {
        val pin = buildString { repeat(DIGITS) { append(random.nextInt(10)) } }
        active = Active(pin, System.currentTimeMillis() + TTL_MS, 0)
        return pin
    }

    @Synchronized
    fun clear() {
        active = null
    }

    /** Verify a submitted PIN. Consumes the PIN on success (single-use) or when exhausted. */
    @Synchronized
    fun verify(candidate: String): Result {
        val a = active ?: return Result.EXPIRED
        if (System.currentTimeMillis() > a.expiresAt) {
            active = null
            return Result.EXPIRED
        }
        if (a.attempts >= MAX_ATTEMPTS) {
            active = null
            return Result.RATE_LIMITED
        }
        a.attempts++
        return if (candidate == a.pin) {
            active = null
            Result.OK
        } else {
            Result.WRONG
        }
    }
}
